name: powerdope_flutter
version: 1.0.0+1
publish_to: none
description: A power dope app.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  built_collection: ^5.1.0
  built_value: ^8.1.1
  carousel_slider: ^4.0.0
  collection: ^1.15.0
  crypto: ^3.0.1
  dio: ^4.0.0
  expandable: ^5.0.1
  file_picker: ^4.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_downloader: ^1.7.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.6
  geocoding: ^2.0.1
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.8
  google_sign_in:
  hydrated_bloc: ^7.1.0
  intl: ^0.17.0
  path_provider:
  photo_view: ^0.12.0
  powerdope_linter:
    path: ../linter
  powerdope_models:
    path: ../models
  powerdope_services:
    path: ../services
  razorpay_flutter: ^1.2.7
  share_plus: ^2.2.0
  shared_preferences:
  showcaseview: ^1.1.1
  syncfusion_flutter_pdfviewer: ^19.2.62-beta
  url_launcher:
  video_player:
  webview_flutter:
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  build_runner:
  built_value_generator:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/docs/
